### ISSUE TITLE
主分支作为推流端出现奔溃

### ISSUE THREAD

**Issue by Hoke** [qw225967/Bifrost#10]
[tcc client] new available bitrate:1678251
[tcc client] new available bitrate:1691087
[tcc client] new available bitrate:1704152
[tcc client] new available bitrate:1717450
worker: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Thread 3 "worker" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff647e700 (LWP 20072)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) bt 
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cc07f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6d13af1 in __malloc_assert (file=<optimized out>, function=<optimized out>, line=<optimized out>, 
    assertion=<optimized out>) at malloc.c:298
#3  sysmalloc (nb=nb@entry=288, av=av@entry=0x7ffff0000020) at malloc.c:2398
#4  0x00007ffff6d15060 in _int_malloc (av=av@entry=0x7ffff0000020, bytes=bytes@entry=272) at malloc.c:4135
#5  0x00007ffff6d172ad in __GI___libc_malloc (bytes=272) at malloc.c:3075
#6  0x00007ffff76ba258 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055555570305e in __gnu_cxx::new_allocator<void* absl::container_internal::Allocate<8ul, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >(std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> >*, unsigned long)::M>::allocate(unsigned long, void const*) ()
#8  0x0000555555702dc7 in absl::allocator_traits<std::allocator<void* absl::container_internal::Allocate<8ul, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >(std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> >*, unsigned long)::M> >::allocate(std::allocator<void* absl::container_internal::Allocate<8ul, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >(std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> >*, unsigned long)::M>&, unsigned long) ()
#9  0x0000555555702a30 in void* absl::container_internal::Allocate<8ul, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >(std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> >*, unsigned long) ()
#10 0x0000555555702490 in absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::initialize_slots() ()
#11 0x00005555557015ab in absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::resize(unsigned long) ()
#12 0x0000555555700977 in absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::rehash_and_grow_if_necessary() ()
#13 0x00005555556ffa12 in absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::prepare_insert(unsigned long) ()
#14 0x00005555556fe0b0 in std::pair<unsigned long, bool> absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::find_or_prepare_insert<unsigned char>(unsigned char const&) ()
#15 0x00005555556fc71f in std::pair<absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::iterator, bool> absl::container_internal::raw_hash_map<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::try_emplace_impl<unsigned char const&>(unsigned char const&) ()
#16 0x00005555556fb29a in std::pair<absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<unsigned ch---Type <return> to continue, or q <return> to quit---
ar, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::iterator, bool> absl::container_internal::raw_hash_map<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::try_emplace<unsigned char, , 0>(unsigned char const&) ()
#17 0x00005555556f9e42 in decltype (absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>::value(addressof((declval<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*>&>)()))) absl::container_internal::raw_hash_map<absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*>, absl::hash_internal::Hash<unsigned char>, std::equal_to<unsigned char>, std::allocator<std::pair<unsigned char const, bifrost::RtpPacket::TwoBytesExtension*> > >::operator[]<unsigned char, absl::container_internal::FlatHashMapPolicy<unsigned char, bifrost::RtpPacket::TwoBytesExtension*> >(unsigned char const&) ()
#18 0x00005555556f69cf in bifrost::RtpPacket::SetExtensions(unsigned char, std::vector<bifrost::RtpPacket::GenericExtension, std::allocator<bifrost::RtpPacket::GenericExtension> > const&) ()
#19 0x00005555556c118d in bifrost::FakeDataProducer::GetRtpExtensions(std::shared_ptr<bifrost::RtpPacket>&) ()
#20 0x00005555556c1006 in bifrost::FakeDataProducer::CreateData() ()
#21 0x00005555556c6ed2 in bifrost::BifrostPacer::OnTimer(bifrost::UvTimer*) ()
#22 0x00005555556e269c in bifrost::UvTimer::OnUvTimer() ()
#23 0x00005555556e227d in bifrost::onTimer(uv_timer_s*) ()
#24 0x000055555573737b in uv.run_timers ()
#25 0x000055555573c9bc in uv_run ()
#26 0x00005555556e3d61 in bifrost::UvLoop::RunLoop() ()
#27 0x0000555555703cf6 in bifrost::Transport::Run() ()
#28 0x000055555573311d in PublishTransport0(std::shared_ptr<bifrost::Transport>&) ()
#29 0x0000555555733fe2 in void std::__invoke_impl<void, void (*)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> > >(std::__invoke_other, void (*&&)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> >&&) ()
#30 0x000055555573391b in std::__invoke_result<void (*)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> > >::type std::__invoke<void (*)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> > >(void (*&&)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> >&&) ()
#31 0x0000555555735c3f in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> > > >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#32 0x0000555555735b6f in std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> > > >::operator()() ()
#33 0x0000555555735aae in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<bifrost::Transport>&), std::reference_wrapper<std::shared_ptr<bifrost::Transport> > > > >::_M_run() ()
#34 0x00007ffff76e466f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#35 0x00007ffff7bbb6db in start_thread (arg=0x7ffff647e700) at pthread_create.c:463
#36 0x00007ffff6da161f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by qw225967** [comment]
由于静态区共享问题导致的崩溃，已修复
